config {
  type: "table",
  schema: "staging_aemet",
  name: "stg_aemet_hrs"
}
 
select nombre,
  provincia,
  cast(codigo as int) as codigo,
  cast(LEFT(fecha, 10) AS DATE) as fecha,
  periodo,
  cast(precipitaciones as int) as precipitaciones,
  estado_del_cielo,
  cast(temperatura_maxima as int) as temperatura_maxima,
  cast(temperatura_minima as int) as temperatura_minima
from ${ref('aemetextractionhelena_raw')}